Repository Rizky-Iqbal36/socmed-scrapper, pull requests merged in 2022-10, with the labels that each got.

#1 Project Commit
  .eslintrc.js
  .gitignore
  .prettierrc.json
  LICENSE
  README.md
  jest.config.js
  package-lock.json
  package.json
  src/__test__/integration/api/api.test.ts
  src/__test__/integration/unit/unit.test.ts
  src/__test__/util/createApp.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  tsconfig.build.json
  tsconfig.json
Labels: hacktoberest-accepted, hacktoberfest

#6 App's testing environment
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/__test__/integration/api/api.test.ts
  src/__test__/integration/api/health-check.test.ts
  src/__test__/integration/unit/unit.test.ts
  src/__test__/util/createApp.ts
  src/app.controller.ts
  src/app.module.ts
  src/app/config/index.ts
  src/controllers/app.controller.ts
  src/controllers/index.ts
  src/services/app.service.ts
  src/services/index.ts
Labels: hacktoberfest-accepted, hacktoberfest

#8 continues integration add automation execute integration test
  .github/workflows/integration-test.yml
  package.json
Labels: hacktoberfest-accepted, hacktoberfest

#13 Ahmad Fatihin - Issue-4 / documentation template for issue
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: hacktoberfest-accepted, hacktoberfest

#15 Update the readme.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest
